# Excercise 1: Linear regression

Please write here your name and student id: Joonas Lehikoinen 1607956

File bb.csv contains synthetic data about basketball player statistics. Columns Height, Years, Draftposition 
should be used to predict the value in column Pointsaverage. To do this the data should be read in, cleaned and scaled. Then a linear model that fits with the data is created. Last step is to predict the points average for Lauri Markkanen during his first years with Chicago Bulls. See https://en.wikipedia.org/wiki/Lauri_Markkanen for more information on Lauri.

In [1]:
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from numpy import genfromtxt

Read in the file "bb.csv" using numpy genfromtext() function.

In [2]:
#bb_data = ...
# YOUR CODE HERE

#raise NotImplementedError()
bb_data = genfromtxt('bb.csv', delimiter=',',skip_header=1,dtype=float)

In [3]:
# Checking that data dimensions are correct.

assert(bb_data.shape[0] == 30)
assert(bb_data.shape[1] == 4)

Check that data makes sense by seeing if all values are non-negative etc. Remove any illegal (possibly corrupted) rows of data with numpy.delete(), for example. Assign cleaned data to variable bb_data_cleaned.

In [4]:
#bb_data_cleaned = 
# YOUR CODE HERE

#bb_data = bb_data[~np.isnan(bb_data)]
#bb_data=np.delete(bb_data,np.where(~bb_data.any(axis=1))[0], axis=0) #Toimiii
#bb_data=bb_data[~removeZN]

print(stats.describe(bb_data[0]))
print(bb_data)

k=0
for i in range(len(bb_data)):
    for j in range(len(bb_data[k])):
        
        if(bb_data[k][j]<=0):
            bb_data=np.delete(bb_data,k,0)
            k-=1
            print('delete')
    k+=1
             
bb_data.shape
bb_data_cleaned=bb_data
#raise NotImplementedError()

DescribeResult(nobs=4, minmax=(1.0, 212.0), mean=61.5075, variance=10132.676891666668, skewness=1.1318073901072683, kurtosis=-0.6839932646441302)
[[212.      1.     21.     12.03 ]
 [200.      5.     15.     14.45 ]
 [195.      6.      3.     27.725]
 [211.      2.     12.     16.665]
 [206.      8.      8.     27.49 ]
 [216.      3.     11.     16.19 ]
 [222.      1.     27.      1.78 ]
 [182.     11.      2.     34.18 ]
 [199.      2.      2.     28.485]
 [209.     10.     14.     20.235]
 [211.      4.     25.      5.065]
 [218.      6.     21.     -1.   ]
 [220.      5.      1.     30.35 ]
 [219.      9.     28.      6.235]
 [200.     11.      3.     32.55 ]
 [203.     15.      8.     30.295]
 [207.      1.     16.      8.455]
 [189.      6.     11.     20.435]
 [198.      4.     14.     16.77 ]
 [193.      8.     11.     22.595]
 [198.      3.      1.     27.92 ]
 [193.      9.     30.      1.045]
 [211.     12.     22.      9.165]
 [  0.     11.     19.     11.48 ]
 [209.      4.

In [5]:
assert(bb_data_cleaned.shape[0] == 28)
assert(bb_data_cleaned.shape[1] == 4)
assert(np.sum(bb_data_cleaned > 0) == 112)

Assign to variable x the features, to y the values we want to predict.

In [6]:
x = bb_data_cleaned[:,:3] 
y = bb_data_cleaned[:,[3]]
print(x)
print(y)
# YOUR CODE HERE
#raise NotImplementedError()

[[212.   1.  21.]
 [200.   5.  15.]
 [195.   6.   3.]
 [211.   2.  12.]
 [206.   8.   8.]
 [216.   3.  11.]
 [222.   1.  27.]
 [182.  11.   2.]
 [199.   2.   2.]
 [209.  10.  14.]
 [211.   4.  25.]
 [220.   5.   1.]
 [219.   9.  28.]
 [200.  11.   3.]
 [203.  15.   8.]
 [207.   1.  16.]
 [189.   6.  11.]
 [198.   4.  14.]
 [193.   8.  11.]
 [198.   3.   1.]
 [193.   9.  30.]
 [211.  12.  22.]
 [209.   4.   9.]
 [199.   7.  19.]
 [216.  10.  21.]
 [219.   2.  22.]
 [222.   4.   7.]
 [198.   9.   2.]]
[[12.03 ]
 [14.45 ]
 [27.725]
 [16.665]
 [27.49 ]
 [16.19 ]
 [ 1.78 ]
 [34.18 ]
 [28.485]
 [20.235]
 [ 5.065]
 [30.35 ]
 [ 6.235]
 [32.55 ]
 [30.295]
 [ 8.455]
 [20.435]
 [16.77 ]
 [22.595]
 [27.92 ]
 [ 1.045]
 [ 9.165]
 [17.435]
 [15.935]
 [18.04 ]
 [ 3.785]
 [27.43 ]
 [27.32 ]]


In [7]:
assert(x.shape[0] == 28)
assert(x.shape[1] == 3)
assert(y.shape[0] == 28)

Scale x data with sklearn StandardScaler.

In [8]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_x = scaler.fit(x).transform(x)
# YOUR CODE HERE
#raise NotImplementedError()

In [9]:
eps = 0.0001
assert(np.sum(scaled_x.mean(axis=0)) < eps)
assert(np.sum(scaled_x.std(axis=0)) < 3 + eps)

Split the data into training (x_train, y_train) and test (x_test, y_test) sets with the test set size 30% of all data.

In [10]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test =train_test_split(x,y, test_size=0.3,random_state=8) 

np.random.seed(42) # Please do not remove
# YOUR CODE HERE
#raise NotImplementedError()

In [11]:
assert(x_train.shape[0] == 19 and x_test.shape[0] == 9)
assert(y_train.shape[0] == 19 and y_test.shape[0] == 9)
assert(x_train.shape[1] == 3 and x_test.shape[1] == 3)

Create a linear model.

Assign the R^2 score of the model computed with test set to variable r2test.

In [12]:
model = linear_model.LinearRegression()
model.fit(x_train,y_train)

# ...
r2test = model.score(x_test,y_test)
# YOUR CODE HERE
#raise NotImplementedError()

In [13]:
assert(r2test - 0.8161738892 < eps)

Predict Lauri Markkanen's point average for seasons 17-18 and 18-19 using your model. Assign your predictions to variables lauri1718 and lauri1819.

In [14]:
#model.predict()
#lauri1718=None
lauri1718 =model.predict(np.array([[213,0,7]]))
#lauri1718 =model.predict(lauri1718)
print(lauri1718)
lauri1819 = model.predict(np.array([[213,1,7]]))
print(lauri1819)
# YOUR CODE HERE
#raise NotImplementedError()

[[19.08897082]]
[[20.05437505]]


In [15]:
assert(lauri1718 - 19.78996201 < eps)
assert(lauri1819 - 20.76399068 < eps)